'use client';
import {ResponsiveContainer,AreaChart,Area,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,BarChart,Bar,ScatterChart,Scatter,Cell,Legend} from 'recharts';
const axis={fontSize:10,fill:'var(--chart-axis)'};
const tooltip={background:'var(--surface)',border:'1px solid var(--line)',borderRadius:6,fontSize:12,color:'var(--ink)'};
export function TimeChart({data,height=230,forecast=false}:{data:Record<string,unknown>[];height?:number;forecast?:boolean}){return <div role="img" aria-label={forecast?'Predicted heat index over the forecast horizon, dashed line; empirical interval bounds':'Heat index over time in degrees Celsius'} style={{height,width:'100%',minWidth:0}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-17,right:15,top:20,bottom:0}}><defs><linearGradient id="heatFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-heat)" stopOpacity={.17}/><stop offset="100%" stopColor="var(--chart-heat)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="var(--line)"/><XAxis dataKey="label" tick={axis} axisLine={false} tickLine={false} minTickGap={35}/><YAxis tick={axis} axisLine={false} tickLine={false} domain={['auto','auto']} tickFormatter={v=>`${Number(v).toFixed(0)}°`}/><Tooltip contentStyle={tooltip} formatter={v=>[`${Number(v).toFixed(1)}°C`,'Heat index']}/><Area type="monotone" dataKey="heat_index" stroke="var(--chart-heat)" strokeWidth={2} strokeDasharray={forecast?'5 4':undefined} fill="url(#heatFill)" isAnimationActive={false}/>{forecast&&<><Area dataKey="upper" stroke="#ba9c87" strokeDasharray="2 4" fill="none"/><Area dataKey="lower" stroke="#ba9c87" strokeDasharray="2 4" fill="none"/></>}</AreaChart></ResponsiveContainer></div>}
export function ColumnChart({data,x='label',y='value',color='var(--chart-heat)',height=245}:{data:Record<string,unknown>[];x?:string;y?:string;color?:string;height?:number}){return <div role="img" aria-label={`${y.replaceAll('_',' ')} by ${x}`} style={{height,minWidth:0}}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{left:-10,right:15,top:15,bottom:15}}><CartesianGrid stroke="var(--line)" strokeDasharray="3 4" vertical={false}/><XAxis dataKey={x} tick={axis} tickLine={false} axisLine={false}/><YAxis tick={axis} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltip} formatter={v=>Number(v).toFixed(2)}/><Bar dataKey={y} fill={color} radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>}
export function ScatterPlot({data,x,y,color='#cb7950'}:{data:Record<string,unknown>[];x:string;y:string;color?:string}){return <div role="img" aria-label={`${y.replaceAll('_',' ')} versus ${x.replaceAll('_',' ')}`} style={{height:260,minWidth:0}}><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{left:0,right:25,top:20,bottom:25}}><CartesianGrid stroke="var(--line)" strokeDasharray="3 4"/><XAxis type="number" dataKey={x} name={x.replaceAll('_',' ')} tick={axis} domain={['auto','auto']} label={{value:x.replaceAll('_',' '),position:'bottom',fontSize:10,fill:'var(--chart-axis)'}}/><YAxis type="number" dataKey={y} name={y.replaceAll('_',' ')} tick={axis} domain={['auto','auto']}/><Tooltip contentStyle={tooltip} cursor={{strokeDasharray:'3 3'}}/><Scatter data={data} fill={color} fillOpacity={.6} isAnimationActive={false}/></ScatterChart></ResponsiveContainer></div>}
export function ComparisonChart({data}:{data:Record<string,unknown>[]}){return <div role="img" aria-label="City comparison of average and peak heat index" style={{height:300,minWidth:0}}><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="name" tick={axis}/><YAxis tick={axis}/><Tooltip contentStyle={tooltip}/><Legend wrapperStyle={{fontSize:12}}/><Bar name="Average heat index °C" dataKey="heat_index" fill="var(--chart-heat)" radius={[4,4,0,0]}/><Bar name="Peak heat index °C" dataKey="peak" fill="var(--chart-secondary)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>}


