import {Bundle,Config,Row,Observation} from './types';
export const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
export const compact=(n:number)=>Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
export function heatIndex(c:number,r:number){const t=c*1.8+32;const simple=.5*(t+61+(t-68)*1.2+r*.094);let hi=-42.379+2.04901523*t+10.14333127*r-.22475541*t*r-.00683783*t*t-.05481717*r*r+.00122874*t*t*r+.00085282*t*r*r-.00000199*t*t*r*r;if(r<13&&t>=80&&t<=112)hi-=((13-r)/4)*Math.sqrt((17-Math.abs(t-95))/17);if(r>85&&t>=80&&t<=87)hi+=((r-85)/10)*((87-t)/5);return (((simple+t)/2>=80?hi:simple)-32)/1.8}
export function score(hi:number,density:number,vegetation:number,built:number,c:Config){const v:Record<string,number>={heat:hi,population_density:density,vegetation_deficit:100-vegetation,built_up:built};return Object.entries(v).reduce((s,[k,v])=>{if(!c.weights[k])return s;const [lo,high]=c.normalization[k];return s+c.weights[k]*100*Math.max(0,Math.min(1,(v-lo)/(high-lo)))},0)}
export function category(value:number,c:Config){return [...c.risk_thresholds].reverse().find(x=>value>=x.min)??c.risk_thresholds[0]}
export function rowsAt(b:Bundle,date:string,hour:number):Row[]{return b.observations.filter(o=>o.timestamp.slice(0,10)===date&&Number(o.timestamp.slice(11,13))===hour).map(o=>{const city=b.cities.find(c=>c.city_id===o.city_id)!;const index=score(o.heat_index,city.population_density,city.vegetation,city.built_up,b.config);return {...city,...o,exposure_index:index,risk:category(index,b.config).label,exposed_population:index>=b.config.elevated_min?city.population:0,source_heat_index:null}})}
export const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN;
export function groupObservations(rows:Observation[],group:'hour'|'day'|'week'|'month'|'year'){const map=new Map<string,Observation[]>();for(const r of rows){let key=r.timestamp.slice(0,10);if(group==='hour')key=r.timestamp.slice(0,13)+':00';if(group==='month')key=key.slice(0,7);if(group==='year')key=key.slice(0,4);if(group==='week'){const d=new Date(key+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));key=d.toISOString().slice(0,10)}map.set(key,[...(map.get(key)??[]),r])}return [...map].sort(([a],[b])=>a.localeCompare(b)).map(([label,r])=>({label,heat_index:mean(r.map(x=>x.heat_index)),temperature:mean(r.map(x=>x.temperature)),humidity:mean(r.map(x=>x.humidity))}))}
export function saveCSV(rows:Record<string,unknown>[],name:string){if(!rows.length)return;const keys=Object.keys(rows[0]);const escape=(v:unknown)=>'"'+String(typeof v==='number'&&!Number.isFinite(v)?'':v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv=[keys.map(escape).join(','),...rows.map(r=>keys.map(k=>escape(r[k])).join(','))].join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}

